name: Build, test and deliver container

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 15 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
        
      - name: Build, test and package project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=julesd2001_afstand-edge-service
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/afstand-edge-service .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/afstand-edge-service
